name: 🚀 Deploy

on:
  # Run on each push to main
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node LTS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: 🛠️ Build
        env:
          REACT_APP_FIREBASE_CONFIG_JSON: ${{ secrets.FIREBASE_CONFIG_JSON }}
          REACT_APP_SERVER_URI: http://localhost:9001/graphql
        run: npm run build

      - name: ⚡ Test
        env:
          REACT_APP_FIREBASE_CONFIG_JSON: ${{ secrets.FIREBASE_CONFIG_JSON }}
          REACT_APP_SERVER_URI: http://localhost:9001/graphql
        run: npm run test

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/frontend/build
          cname: flocker.us
