name: ⚡ Build Format Lint Test

on:
  # Run on each push to main
  push:
    branches: [main]

  # Run on each push to a PR
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-format-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node LTS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: ${{ !env.ACT && 'npm' || '' }}

      - name: Install dependencies
        run: npm install

      - name: 🛠️ Build
        run: npm run build

      - name: ⚡ Format
        run: |
          npm run format
          git diff --exit-code

      - name: ⚡ Lint
        run: |
          npm run lint
          git diff --exit-code

      - name: ⚡ Test
        env:
          REACT_APP_FIREBASE_CONFIG_JSON: ${{ secrets.FIREBASE_CONFIG_JSON }}
          REACT_APP_SERVER_URI: ${{ secrets.SERVER_URI }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm run test
